name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Use Gradle Action and tell it which Gradle version to install
      - name: Build with Gradle (install specific Gradle)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.6"    # <- installs Gradle 8.6 on the runner
          arguments: "assembleDebug"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: usc-webview-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
